### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [1]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tensorflow-gpu
  Running setup.py clean for tensorflow-gpu
Failed to build tensorflow-gpu
  error: subprocess-exited-with-error
  
  × Running setup.py install for tensorflow-gpu did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Running setup.py install for tensorflow-gpu ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> tensorflow-gpu

note: This is an issue with the package mentioned above, not pip.
hint: See above for outpu

In [2]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [3]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [5]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[261, 193, 331, 271], [261, 193, 331, 281], [261, 460, 331, 208], [178, 455, 235, 335, 54], [178, 455, 235, 335, 448], [427, 261, 67, 331, 381], [230, 68, 392, 335]]


### Word Embedding Representation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
## Pre padding- padding in the beginning
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 261 193 331 271]
 [  0   0   0   0 261 193 331 281]
 [  0   0   0   0 261 460 331 208]
 [  0   0   0 178 455 235 335  54]
 [  0   0   0 178 455 235 335 448]
 [  0   0   0 427 261  67 331 381]
 [  0   0   0   0 230  68 392 335]]


In [10]:
## 10 feature dimension
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
##'the glass of milk'
embedded_docs[0]

array([  0,   0,   0,   0, 261, 193, 331, 271], dtype=int32)

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 194ms/step


array([[-6.81757927e-04, -1.64789185e-02,  2.38439180e-02,
        -5.88653237e-03,  1.10176429e-02, -4.28105853e-02,
        -4.28871624e-02,  4.70985211e-02, -3.14983949e-02,
        -9.87313688e-04],
       [-6.81757927e-04, -1.64789185e-02,  2.38439180e-02,
        -5.88653237e-03,  1.10176429e-02, -4.28105853e-02,
        -4.28871624e-02,  4.70985211e-02, -3.14983949e-02,
        -9.87313688e-04],
       [-6.81757927e-04, -1.64789185e-02,  2.38439180e-02,
        -5.88653237e-03,  1.10176429e-02, -4.28105853e-02,
        -4.28871624e-02,  4.70985211e-02, -3.14983949e-02,
        -9.87313688e-04],
       [-6.81757927e-04, -1.64789185e-02,  2.38439180e-02,
        -5.88653237e-03,  1.10176429e-02, -4.28105853e-02,
        -4.28871624e-02,  4.70985211e-02, -3.14983949e-02,
        -9.87313688e-04],
       [-2.86906119e-02, -4.95331548e-02,  2.75073387e-02,
         3.14762704e-02,  3.82595770e-02,  4.53503765e-02,
         4.52376343e-02, -2.62220148e-02,  1.52507760e-02,
        -9.

In [15]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 40ms/step
[[[-6.81757927e-04 -1.64789185e-02  2.38439180e-02 -5.88653237e-03
    1.10176429e-02 -4.28105853e-02 -4.28871624e-02  4.70985211e-02
   -3.14983949e-02 -9.87313688e-04]
  [-6.81757927e-04 -1.64789185e-02  2.38439180e-02 -5.88653237e-03
    1.10176429e-02 -4.28105853e-02 -4.28871624e-02  4.70985211e-02
   -3.14983949e-02 -9.87313688e-04]
  [-6.81757927e-04 -1.64789185e-02  2.38439180e-02 -5.88653237e-03
    1.10176429e-02 -4.28105853e-02 -4.28871624e-02  4.70985211e-02
   -3.14983949e-02 -9.87313688e-04]
  [-6.81757927e-04 -1.64789185e-02  2.38439180e-02 -5.88653237e-03
    1.10176429e-02 -4.28105853e-02 -4.28871624e-02  4.70985211e-02
   -3.14983949e-02 -9.87313688e-04]
  [-2.86906119e-02 -4.95331548e-02  2.75073387e-02  3.14762704e-02
    3.82595770e-02  4.53503765e-02  4.52376343e-02 -2.62220148e-02
    1.52507760e-02 -9.40449536e-05]
  [-2.09263209e-02  1.61078237e-02 -2.28954200e-02 -9.74422693e-03
    1.02500543e-02 -1.17979534e

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 6654,  998, 8966, 1609])

In [ ]:
print(model.predict(embedded_docs)[0])

[[-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.03786323 -0.02628061  0.02974111 -0.03307171  0.0271405   0.00945134
   0.02378127  0.04176904  0.00514941  0.0152082 ]
 [ 0.04834186  0.04388311 -0.02802253 -0.01475487 -0.01212303  0.03762435
  -0.01166249 -0.02141088  0.04654533  0.01537322]
 [ 0.03276015 -0.00637691  0.03907344 -0.01912468  0.02177186 -0.04630325
   0.00800942 -0.03115667 -0.00486455 -0.04843524]
 [-0.04173617  0.03438064  0.02880521 -0.01896455  0.0323303  -0.00109453
  -0.01675171 -0.00941917 -0.03309294 -0.04779492]]

In [16]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [17]:
vocab_size=300

In [18]:
one_hot_encode=[one_hot(worrd,vocab_size)for worrd in sent]
one_hot_encode

[[87, 60, 4, 7, 289, 274],
 [265, 106, 4, 237, 9, 166],
 [120, 276, 78, 127],
 [87, 165, 4, 41, 87, 247],
 [238, 18, 104, 4, 237, 9, 166],
 [230, 4, 237, 9, 111, 220]]

In [19]:
#Padding
sen_len_max=10
sent_padding_pre=pad_sequences(one_hot_encode,maxlen=sen_len_max,padding='pre')
sent_padding_post=pad_sequences(one_hot_encode,maxlen=sen_len_max,padding='post')

In [20]:
print(sent_padding_pre)

[[  0   0   0   0  87  60   4   7 289 274]
 [  0   0   0   0 265 106   4 237   9 166]
 [  0   0   0   0   0   0 120 276  78 127]
 [  0   0   0   0  87 165   4  41  87 247]
 [  0   0   0 238  18 104   4 237   9 166]
 [  0   0   0   0 230   4 237   9 111 220]]


In [21]:
print(sent_padding_post)

[[ 87  60   4   7 289 274   0   0   0   0]
 [265 106   4 237   9 166   0   0   0   0]
 [120 276  78 127   0   0   0   0   0   0]
 [ 87 165   4  41  87 247   0   0   0   0]
 [238  18 104   4 237   9 166   0   0   0]
 [230   4 237   9 111 220   0   0   0   0]]


In [22]:
# Defining feature dimensions

feat_dim=19

In [23]:
model1=Sequential()
model1.add(Embedding(vocab_size,feat_dim,input_length=sen_len_max))
model1.compile('adam','mse')

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [25]:
print(model.predict(sent_padding_pre))

1/1 [==============================] - 0s 24ms/step
[[[-0.00068176 -0.01647892  0.02384392 -0.00588653  0.01101764
   -0.04281059 -0.04288716  0.04709852 -0.03149839 -0.00098731]
  [-0.00068176 -0.01647892  0.02384392 -0.00588653  0.01101764
   -0.04281059 -0.04288716  0.04709852 -0.03149839 -0.00098731]
  [-0.00068176 -0.01647892  0.02384392 -0.00588653  0.01101764
   -0.04281059 -0.04288716  0.04709852 -0.03149839 -0.00098731]
  [-0.00068176 -0.01647892  0.02384392 -0.00588653  0.01101764
   -0.04281059 -0.04288716  0.04709852 -0.03149839 -0.00098731]
  [ 0.01222873  0.0053253   0.02533319  0.00388135  0.03553779
    0.02894754  0.02753076 -0.00484756  0.02131828 -0.02338705]
  [-0.04508493  0.03573865  0.02067837 -0.01706032 -0.02427666
    0.02224289  0.0052883  -0.01559188  0.01563894 -0.03318279]
  [ 0.0355719  -0.03028131 -0.04023107 -0.04406783  0.02536868
    0.03637442  0.01994175  0.02793651  0.04174507  0.04114627]
  [ 0.02684661 -0.01622162 -0.03613888  0.03142497  0.00358

In [26]:
print(model.predict(sent_padding_post))

1/1 [==============================] - 0s 18ms/step
[[[ 0.01222873  0.0053253   0.02533319  0.00388135  0.03553779
    0.02894754  0.02753076 -0.00484756  0.02131828 -0.02338705]
  [-0.04508493  0.03573865  0.02067837 -0.01706032 -0.02427666
    0.02224289  0.0052883  -0.01559188  0.01563894 -0.03318279]
  [ 0.0355719  -0.03028131 -0.04023107 -0.04406783  0.02536868
    0.03637442  0.01994175  0.02793651  0.04174507  0.04114627]
  [ 0.02684661 -0.01622162 -0.03613888  0.03142497  0.00358617
    0.04119452 -0.03729244  0.01851816 -0.02541555 -0.03263604]
  [ 0.02273438 -0.01303373 -0.0371555   0.02201032  0.00678177
   -0.04319274 -0.01017833  0.00465897 -0.02662471 -0.04877584]
  [-0.03772891  0.01300352  0.01803805  0.02979309 -0.0006564
    0.0258806  -0.01950343 -0.02119421  0.02539081  0.03951517]
  [-0.00068176 -0.01647892  0.02384392 -0.00588653  0.01101764
   -0.04281059 -0.04288716  0.04709852 -0.03149839 -0.00098731]
  [-0.00068176 -0.01647892  0.02384392 -0.00588653  0.011017